mode: "production"
httpDomain: "localhost"
httpPort: "8080"
couchDBPort: "5984"
dbUrl: "brewing_support_db"
dbPort: "5432"
dbUser: "brewing_support"
dbPassword: "brewing_support"
dbName: "brewing_supportdb"
secretKey: "secret"
loginExpTime: 24